### ISSUE TITLE
Cannot find config file

### ISSUE THREAD

**Issue by protoEvangelion** [markfinger/webpack-build#17]
I am getting an error: `Cannot find config file ./webpack.config` .  

My webpack file is  on the same level as my server and I have tried many variations of the 'webpack.config' string.  

Should the **setup** of the webpack-build package go in a separate file, or should it be placed in the server file?

**Comment by markfinger** [comment]
If you're having problems resolving the config file, it suggests that your process is running with a different working directory and node fails to resolve the relative path to the file.

I'd recommend changing your config file path to an absolute path. Something like `require.resolve('./webpack.config')` should provide it.

Otherwise, you could try tinkering with the `NODE_PATH` env var, but I'm not sure how helpful that would be.

Best of luck.
